"use strict";
let nValor;
let sValor;
let uValor;
nValor = 15;
sValor = '2025';
uValor = 10;
nValor = Number.parseInt(sValor);
sValor = nValor.toString();
console.log(typeof nValor);
console.log(typeof sValor);
